apiVersion: apps/v1
kind: Deployment
metadata:
  name: noisy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: noisy
  template:
    metadata:
      labels:
        app: noisy
        sstk_meta_sumo: "true"
    spec:
      securityContext:
        runAsUser: 999
      containers:
      - name: noisy
        image: docker.pkg.github.com/wayne-folkes/noisy-app/noisy:latest
      imagePullSecrets:
        - name: regcred
